version: '2'
services:
  status-server:
    build: .
    container_name: status-server
    network_mode: host
    ports:
      - 5000:5000
    image: reynard
    command: reynard_eff_status_server.py -p 5000
  effcam-server:
    build: .
    container_name: effcam-server
    network_mode: host
    ports:
      - 5002:5002
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    image: reynard
    user: 50000:50000
    group_add:
      - 999
    command: >
      reynard_effcam_server.py --port 5002
      --status_ip=localhost --status_port=5000
      --backend ubi:localhost:5003
      --log_level DEBUG
  ubi-server:
    build: .
    container_name: ubi-server
    network_mode: host
    ports:
      - 5003:5003
    image: reynard
    command: reynard_ubi_server.py --port 5003 --log_level DEBUG
    user: 50000:50000
    group_add:
      - 999